
EXCEPTION_HANDLER=None
DEBUG=True
LOG_LEVEL='INFO'
BINARY_SUPPORT=True
CONTEXT_HEADER_MAPPINGS={}
DOMAIN=None
BASE_PATH=None
ENVIRONMENT_VARIABLES={}
API_STAGE='dev'
PROJECT_NAME='test_msk'
SETTINGS_FILE=None
DJANGO_SETTINGS=None
AWS_EVENT_MAPPING={'arn:aws:kafka:sa-east-1:123456789012:cluster/vpc-2priv-2pub/751d2973-a626-431c-9d4e-d7975eb44dd7-2:test_msk': 'tests.test_handler.handle_msk_intent'}
AWS_BOT_EVENT_MAPPING={}
COGNITO_TRIGGER_MAPPING={}
ASYNC_RESPONSE_TABLE=''